source "https://rubygems.org"

gem "jekyll"

group :jekyll_plugins do
    gem 'jekyll-spaceship'
    gem 'execjs'
end
#per: https://github.com/linjer/jekyll-katex
#per: https://jekyllrb.com/docs/ruby-101/
